<?php
    $social_network_icon_mapping = [
        'fivehundredpx' => 'fa-500px',
        '500px' => 'fa-500px', // Backward compatibility
        'amazon' => 'fa-amazon',
        'angellist' => 'fa-angellist',
        'apple' => 'fa-apple',
        'artstation' => 'fa-artstation',
        'behance' => 'fa-behance',
        'bitbucket' => 'fa-bitbucket',
        'bluesky' => 'fa-bluesky',
        'blogger' => 'fa-blogger',
        'codepen' => 'fa-codepen',
        'deviantart' => 'fa-deviantart',
        'diaspora' => 'fa-diaspora',
        'digg' => 'fa-digg',
        'discord' => 'fa-discord',
        'dribbble' => 'fa-dribbble',
        'dropbox' => 'fa-dropbox',
        'drupal' => 'fa-drupal',
        'etsy' => 'fa-etsy',
        'facebook' => 'fa-facebook-f',
        'fediverse' => 'fa-mastodon',
        'figma' => 'fa-figma',
        'flickr' => 'fa-flickr',
        'foursquare' => 'fa-foursquare',
        'git' => 'fa-git',
        'github' => 'fa-github',
        'gitlab' => 'fa-gitlab',
        'goodreads' => 'fa-goodreads',
        'google' => 'fa-google',
        'google-play' => 'fa-google-play',
        'hacker-news' => 'fa-hacker-news',
        'houzz' => 'fa-houzz',
        'instagram' => 'fa-instagram',
        'jsfiddle' => 'fa-jsfiddle',
        'kaggle' => 'fa-kaggle',
        'kickstarter' => 'fa-kickstarter',
        'lastfm' => 'fa-lastfm',
        'line' => 'fa-line',
        'linkedin' => 'fa-linkedin-in',
        'mastodon' => 'fa-mastodon',
        'medium' => 'fa-medium',
        'meetup' => 'fa-meetup',
        'messenger' => 'fa-facebook-messenger',
        'nextdoor' => 'fa-nextdoor',
        'npm' => 'fa-npm',
        'orcid' => 'fa-orcid',
        'patreon' => 'fa-patreon',
        'paypal' => 'fa-paypal',
        'peertube' => 'fa-peertube',
        'pinterest' => 'fa-pinterest-p',
        'producthunt' => 'fa-product-hunt',
        'python' => 'fa-python',
        'qq' => 'fa-qq',
        'quora' => 'fa-quora',
        'reddit' => 'fa-reddit',
        'researchgate' => 'fa-researchgate',
        'reverbnation' => 'fa-reverbnation',
        'rss' => 'fa-rss',
        'salesforce' => 'fa-salesforce',
        'sass' => 'fa-sass',
        'sharp' => 'fa-sharp',
        'shopify' => 'fa-shopify',
        'skype' => 'fa-skype',
        'slack' => 'fa-slack',
        'snapchat' => 'fa-snapchat',
        'soundcloud' => 'fa-soundcloud',
        'sourcetree' => 'fa-sourcetree',
        'spotify' => 'fa-spotify',
        'stackexchange' => 'fa-stack-exchange',
        'stackoverflow' => 'fa-stack-overflow',
        'strava' => 'fa-strava',
        'stripe' => 'fa-stripe',
        't2' => 'fa-t2',
        'teamspeak' => 'fa-teamspeak',
        'telegram' => 'fa-telegram',
        'threads' => 'fa-threads',
        'tiktok' => 'fa-tiktok',
        'trello' => 'fa-trello',
        'tripadvisor' => 'fa-tripadvisor',
        'tumblr' => 'fa-tumblr',
        'twitch' => 'fa-twitch',
        'twitter' => 'fa-x-twitter',
        'ubuntu' => 'fa-ubuntu',
        'untappd' => 'fa-untappd',
        'usps' => 'fa-usps',
        'viadeo' => 'fa-viadeo',
        'vimeo' => 'fa-vimeo-v',
        'waze' => 'fa-waze',
        'weibo' => 'fa-weibo',
        'wechat' => 'fa-wechat',
        'weixin' => 'fa-weixin',
        'whatsapp' => 'fa-whatsapp',
        'wikipedia' => 'fa-wikipedia-w',
        'wordpress' => 'fa-wordpress',
        'wpexplorer' => 'fa-wpexplorer',
        'xing' => 'fa-xing',
        'yahoo' => 'fa-yahoo',
        'yelp' => 'fa-yelp',
        'youtube' => 'fa-youtube',
        'zhihu' => 'fa-zhihu'
    ];

    while ( have_rows( 'global_header_menu_social_links', 'option' ) ) :
        the_row();

        $_network_field = get_sub_field( 'social_network' );
        $network_icon = $social_network_icon_mapping[$_network_field];
        printf( '<a href="%s" target="%s" rel="nofollow" aria-label="' . esc_attr( $_network_field ) . '" class="network -unlink %s">', esc_url( get_sub_field( 'url' ) ), '_blank', esc_attr( $_network_field ) );
            ?>
                <i class="fa-brands <?php echo $network_icon; ?>"></i>
            <?php
        echo '</a>';
    endwhile;
?>
